### ISSUE TITLE
Weird behavior with end of DST and get_next method

### ISSUE THREAD

**Issue by jpinsolle-bc** [pallets-eco/croniter#25] opened 2022-10-03 10:30 UTC
Hello,

I got a weird behavior with the end of DST (Daily Saving Time) when `croniter` computes next occurrences.

With timezone Europe/Paris, at 2022-10-30T03:00:00+02:00, it will be 2022-10-30T02:00:00+01:00.
In this example, I simulate a date before the DST (midnight)
```python
with freeze_time("2022-10-30T00:00:00+02:00"):
    now = datetime.now(tz=timezone.utc).astimezone(ZoneInfo("Europe/Paris"))
    cron = croniter("00 20 * * *", now)

    next1 = cron.get_next(datetime)
    next2 = cron.get_next(datetime)
    next3 = cron.get_next(datetime)
  
    print("Next1=", next1)
    print("Next2=", next2)
    print("Next3=", next3)

# Next1= 2022-10-30 20:00:00+01:00
# Next2= 2022-10-31 21:00:00+01:00  <-- 21H instead of 20H
# Next3= 2022-11-01 20:00:00+01:00
```

It seems the behavior come from this PR https://github.com/taichino/croniter/pull/92
 
I think there is a bug, what is the expected result for this example ?

**Comment by kiorky** [comment] 2022-10-06 09:08
Exactly, it's a duplicate of  #1 , you may see https://github.com/kiorky/croniter/issues/1#issuecomment-979198501

Thanks for the report !

**Closed as completed by kiorky** 2022-10-06 09:08 UTC
